services:
  restaurantdb:
    image: postgres
  deliverydb:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  
volumes:
    postgres_restaurant:
    postgres_delivery:
    mssql_order:

