services:
  restaurantdb:
    container_name: restaurantdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=RestaurantDb
    restart: always
    ports:
        - "5432:5532"
    volumes:
      - postgres_restaurant:/var/lib/postgresql/data/

  deliverydb:
    container_name: deliverydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DeliveryDb
    restart: always
    ports:
        - "5433:5532"
    volumes:
      - postgres_restaurant:/var/lib/postgresql/data/
 
  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433"
   
